name: app_mi_upc
description: "Integrar la funcionalidad de Mi Upc"
version: 0.0.1
homepage: "https://siipne.policia.gob.ec/indexSiipne.php"

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  get: ^4.6.6 #manejador de estados
  google_fonts: ^6.2.1
  http: ^1.2.2 # Conectar con proveedor - Apis
  local_auth: ^2.3.0 # Acceso Biometrico
  shared_preferences: ^2.3.2
 # intl: ^0.18.0 #Conversion de idiomas, enteros, fechas
  awesome_dialog: ^3.2.1 #Dialogos
  url_launcher: ^6.3.1
  package_info_plus: ^8.0.2 #obtener version code de la app
  connectivity_plus: ^6.0.3 # Verifica a que tipo de red esta conectado
  device_info_plus: ^11.1.0 #Informacion del cell,Version Sistema Operatvivo
  network_info_plus: ^6.1.0 #Obtener ip del celular (se deben asiganr permisos para IOS)
  cached_network_image: ^3.4.1 #Muestra imagenes desde internet y las guarda en cache
  flutter_speed_dial: ^7.0.0 #Botones flotantes, utilizado para el menu (Cerrar sesion y mas)
  permission_handler: ^11.3.1 # Solicita Permisos del dispositivo al usuario (Ubicacion,Galeria.....)
  image: ^4.3.0 #Para trabajar con imagenes de la galeria
  image_picker: ^1.1.2 #Obtener img de la camara o galeria
  share_plus: ^10.1.2 #Compartir aplicacion
  flutter_map: ^7.0.2
  flutter_map_location_marker: ^9.1.1
  latlong2: any
  #vibration: ^1.7.6 #vibracion device
  location: ^7.0.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2 #ubicacion Gps, del dispositivo #error en la actualizacion 8.0.1 No named parameter with the name 'desiredAccuracy'.



dev_dependencies:
  geolocator_android: ^4.5.1
  background_locator_2: ^2.0.6




