name: app_mi_upc
description: "Integrar la funcionalidad de Mi Upc"
version: 0.0.1
homepage: "https://siipne.policia.gob.ec/indexSiipne.php"

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  get: ^4.6.6 #manejador de estados
  google_fonts: ^6.2.1
  http: ^1.2.2 # Conectar con proveedor - Apis
  local_auth: ^2.3.0 # Acceso Biometrico
  shared_preferences: ^2.3.5
  # intl: ^0.18.0 #Conversion de idiomas, enteros, fechas
  awesome_dialog: ^3.2.1 #Dialogos
  url_launcher: ^6.3.1
  package_info_plus: ^8.1.2 #obtener version code de la app
  connectivity_plus: ^6.1.1 # Verifica a que tipo de red esta conectado
  device_info_plus: ^11.2.0 #Informacion del cell,Version Sistema Operatvivo
  network_info_plus: ^6.1.2 #Obtener ip del celular (se deben asiganr permisos para IOS)
  cached_network_image: ^3.4.1 #Muestra imagenes desde internet y las guarda en cache
  permission_handler: ^11.3.1 # Solicita Permisos del dispositivo al usuario (Ubicacion,Galeria.....)
  image: ^4.5.2 #Para trabajar con imagenes de la galeria
  share_plus: ^10.1.3 #Compartir aplicacion





