name: app_mi_upc
description: "Integrar la funcionalidad de Mi Upc"
version: 0.0.1
homepage: "https://siipne.policia.gob.ec/indexSiipne.php"

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  get: ^4.7.2 #manejador de estados - en uso cuando se descragn el proyecto
  local_auth: ^2.3.0 # Acceso Biometrico - en uso cuando se descragn el proyecto


  #Utilidades - device_info.dart
  device_info_plus: ^11.4.0 #Informacion del cell,Version Sistema Operatvivo - en uso cuando se descragn el proyecto
  network_info_plus: ^6.1.4 #Obtener ip del celular (se deben asiganr permisos para IOS) - en uso cuando se descragn el proyecto
  package_info_plus: ^8.3.0 #obtener version code de la app - en uso cuando se descragn el proyecto
  #END Utilidades - device_info.dart

  url_launcher: ^6.3.1 # Abrir Urls- en uso cuando se descragn el proyecto
  share_plus: ^11.0.0 #Compartir aplicacion- en uso cuando se descragn el proyecto
  awesome_dialog: ^3.2.1 #Dialogos- en uso cuando se descragn el proyecto
  image: ^4.5.4 #Para trabajar con imagenes de la galeria - en uso cuando se descragn el proyecto
  shared_preferences: ^2.5.3 #- en uso cuando se descragn el proyecto
  # intl: ^0.18.0 #Conversion de idiomas, enteros, fechas



  connectivity_plus: ^6.1.4 # Verifica a que tipo de red esta conectado


  permission_handler: ^12.0.0+1 # Solicita Permisos del dispositivo al usuario (Ubicacion,Galeria.....)



  http: ^1.3.0 # Conectar con proveedor - Apis
  rxdart: ^0.28.0 # se usa en el check_internet_conexion.dart


flutter:
  assets:
    - assets/img/img/
    - assets/img/icon/
